import { translate } from 'src/dict'
import * as T from 'src/types'
import * as E from 'src/enums'

export const BOOKMARKS_PANEL_CONFIG: T.BookmarksPanelConfig = {
  type: E.PanelType.bookmarks,
  id: '',
  name: '',
  iconSVG: 'icon_bookmarks',
  iconIMGSrc: '',
  iconIMG: '',
  color: 'toolbar',
  lockedPanel: false,
  tempMode: false,
  skipOnSwitching: false,
  rootId: 'root________',
  viewMode: 'tree',
  autoConvert: false,
  srcPanelConfig: null,
}
export const BOOKMARKS_PANEL_STATE: T.BookmarksPanel = {
  ...BOOKMARKS_PANEL_CONFIG,

  class: E.NavItemClass.panel,
  index: -1,
  topOffset: 0,
  leftOffset: 0,
  rightOffset: 0,
  bottomOffset: 0,
  scrollEl: null,
  scrollComponent: null,
  bounds: [],
  hidden: false,
  ready: false,
  bookmarks: [],

  reactive: {
    name: '',
    color: 'toolbar',
    iconSVG: 'icon_bookmarks',
    iconIMG: '',
    hidden: false,
    tooltip: '',
    sel: false,
    len: 0,
    filteredLen: undefined,
    ready: false,

    bookmarkIds: [],
    filteredBookmarkIds: undefined,
    viewMode: 'tree',
    rootOffset: 0,
  },
}

export const TABS_PANEL_CONFIG: T.TabsPanelConfig = {
  type: E.PanelType.tabs,
  id: '',
  name: '',
  color: 'toolbar',
  iconSVG: 'icon_tabs',
  iconIMGSrc: '',
  iconIMG: '',
  lockedPanel: false,
  skipOnSwitching: false,
  noEmpty: false,
  newTabCtx: 'none',
  dropTabCtx: 'none',
  moveRules: [],
  moveExcludedTo: -1,
  bookmarksFolderId: -1,
  newTabBtns: [],
  srcPanelConfig: null,
}
export const TABS_PANEL_STATE: T.TabsPanel = {
  ...TABS_PANEL_CONFIG,

  tabs: [],
  pinnedTabs: [],
  filteredTabs: undefined,
  updatedTabs: [],
  selNewTab: false,
  startTabIndex: -1,
  endTabIndex: -1,
  nextTabIndex: -1,
  scrollRetainer: 0,
  allDiscarded: false,

  class: E.NavItemClass.panel,
  index: -1,
  topOffset: 0,
  leftOffset: 0,
  rightOffset: 0,
  bottomOffset: 0,
  scrollEl: null,
  scrollComponent: null,
  bounds: [],
  hidden: false,
  ready: true,

  reactive: {
    name: '',
    color: 'toolbar',
    iconSVG: 'icon_tabs',
    iconIMG: undefined,
    hidden: false,
    tooltip: '',
    sel: false,
    len: 0,
    filteredLen: undefined,
    ready: true,

    visibleTabIds: [],
    pinnedTabIds: [],
    updated: false,
    selNewTab: false,
    scrollRetainerHeight: 0,
    empty: true,
    allDiscarded: false,
    newTabCtx: 'none',
    newTabBtns: [],
    mediaState: E.MediaState.Silent,
  },
}

export const HISTORY_PANEL_CONFIG: T.HistoryPanelConfig = {
  type: E.PanelType.history,
  id: 'history',
  name: translate('panel.history.title'),
  color: 'toolbar',
  iconSVG: 'icon_clock',
  tempMode: false,
  lockedPanel: false,
  skipOnSwitching: false,
  viewMode: 'history',
}
export const HISTORY_PANEL_STATE: T.HistoryPanel = {
  ...HISTORY_PANEL_CONFIG,

  class: E.NavItemClass.panel,
  index: -1,
  topOffset: 0,
  leftOffset: 0,
  rightOffset: 0,
  bottomOffset: 0,
  scrollEl: null,
  scrollComponent: null,
  bounds: [],
  hidden: false,
  ready: false,

  reactive: {
    name: '',
    color: 'toolbar',
    iconSVG: 'icon_clock',
    iconIMG: undefined,
    hidden: false,
    tooltip: '',
    sel: false,
    len: 0,
    filteredLen: undefined,
    ready: false,
  },
}

export const SYNC_PANEL_CONFIG: T.SyncPanelConfig = {
  type: E.PanelType.sync,
  id: 'sync',
  name: translate('panel.sync.title'),
  color: 'toolbar',
  iconSVG: 'icon_sync',
  tempMode: false,
  lockedPanel: false,
  skipOnSwitching: false,
  viewMode: 'sync',
}
export const SYNC_PANEL_STATE: T.SyncPanel = {
  ...SYNC_PANEL_CONFIG,

  class: E.NavItemClass.panel,
  index: -1,
  topOffset: 0,
  leftOffset: 0,
  rightOffset: 0,
  bottomOffset: 0,
  scrollEl: null,
  scrollComponent: null,
  bounds: [],
  hidden: false,
  ready: false,

  reactive: {
    name: '',
    color: 'toolbar',
    iconSVG: 'icon_sync',
    iconIMG: undefined,
    hidden: false,
    tooltip: '',
    sel: false,
    len: 0,
    filteredLen: undefined,
    ready: false,
  },
}

export const NAV_BTNS_IDS: ID[] = [
  'settings',
  'add_tp',
  'search',
  'create_snapshot',
  'remute_audio_tabs',
  'collapse',
]
