name: pull-request

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review, review_requested]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - name: Setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Lint
        run: |
          npm install
          npm run lint.eslint

  lint-types:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - name: Setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Lint
        run: |
          npm install
          npm run lint.types

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Test
        run: |
          npm install
          npx vitest related --run $(git diff --name-only --relative HEAD^1 HEAD)
